name: env-classificador_avaliacao
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.3.0
  - scikit-learn=1.7.0
  - wordcloud=1.9.4
  - matplotlib=3.10.3
  - pillow=11.2.1
  - numpy=2.3.0